name: Deploy to jas

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy to jas
        run: |
          cd /home/runner/jas
          git pull origin main
          pnpm install
          npx prisma db push
          pnpm run build:swc
          pm2 restart jas
